import { useState } from "react";
import Ic from "../Icons.jsx";

export default function Quiz({ onDone, onRew }) {
  const qs=[{q:"환승연애4 최종 재회 커플이 아닌 조합은?",o:["우진&지연","원규&지현","백현&윤녕","유식&현지"],a:2},{q:"친애하는X 주연 배우는?",o:["한소희","김유정","수지","아이유"],a:1},{q:"유퀴즈온더블럭 MC는?",o:["이경규&강호동","유재석&조세호","신동엽&이수근","전현무&이시언"],a:1},{q:"쇼미더머니의 장르는?",o:["트로트","록","힙합","발라드"],a:2}];
  const [i,sI]=useState(0);const [sc,sSc]=useState(0);const [sel,sSel]=useState(null);const [dn,sDn]=useState(false);
  const pick=k=>{if(sel!==null)return;sSel(k);const ok=k===qs[i].a;if(ok)sSc(s=>s+1);setTimeout(()=>{if(i<qs.length-1){sI(i+1);sSel(null);}else{sDn(true);onRew(sc*15+(ok?15:0),"quiz",{correct:sc+(ok?1:0),total:qs.length});}},700);};
  if(dn)return<div style={{padding:24,textAlign:"center"}}><div style={{fontSize:48,marginBottom:16}}>🎉</div><div style={{fontSize:22,fontWeight:700,color:"#fff",marginBottom:8}}>퀴즈 완료!</div><div style={{fontSize:16,color:"#aaa",marginBottom:16}}>{qs.length}문제 중 {sc}문제 정답</div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:24}}><Ic.Coin /><span style={{fontSize:20,fontWeight:700,color:"#FFD60A"}}>+{sc*15}P</span></div><button onClick={onDone} style={{padding:"12px 32px",background:"#FF2D55",color:"#fff",border:"none",borderRadius:12,fontSize:16,fontWeight:600,cursor:"pointer"}}>돌아가기</button></div>;
  return<div style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><span style={{color:"#aaa",fontSize:14}}>{i+1}/{qs.length}</span><div style={{display:"flex",alignItems:"center",gap:4}}><Ic.Coin /><span style={{color:"#FFD60A",fontWeight:600}}>{sc*15}P</span></div></div><div style={{width:"100%",height:4,background:"#333",borderRadius:2,marginBottom:24}}><div style={{width:`${((i+1)/qs.length)*100}%`,height:"100%",background:"#FF2D55",borderRadius:2,transition:"width .3s"}}/></div><div style={{fontSize:18,fontWeight:600,color:"#fff",marginBottom:24,lineHeight:1.5}}>{qs[i].q}</div><div style={{display:"flex",flexDirection:"column",gap:10}}>{qs[i].o.map((op,k)=>{let bg="#1C1C1E",bd="1px solid #333";if(sel!==null){if(k===qs[i].a){bg="rgba(52,199,89,.15)";bd="1px solid #34C759";}else if(k===sel){bg="rgba(255,45,85,.15)";bd="1px solid #FF2D55";}}return<button key={k} onClick={()=>pick(k)} style={{padding:"14px 16px",background:bg,border:bd,borderRadius:12,color:"#fff",fontSize:15,textAlign:"left",cursor:"pointer"}}><span style={{fontWeight:600,marginRight:10,color:"#888"}}>{String.fromCharCode(65+k)}</span>{op}</button>;})}</div></div>;
}
